[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # Next.js specific settings
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

# Redirect all API routes to Next.js functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs/:splat"
  status = 200

# Redirect all other routes to Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs/:splat"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"